name: 'tekartik_bootstrap'
version: 0.3.0
description: Boostrap wrappers
publish_to: none

environment:
  sdk: ^3.7.0
dependencies:
  pub_semver: ">=2.1.4"
  tekartik_jquery:
    git:
      url: https://github.com/tekartik/jquery.dart
      ref: dart3a
    version: '>=0.3.0'
  tekartik_bootstrap_asset:
    git:
      url: https://github.com/tekartik/bootstrap_asset.dart
      ref: dart3a
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  build_runner: ">=2.4.13"
  build_test: '>=0.10.3'
  build_web_compilers: ">=4.0.11"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
